Danish translation
sugarchain-project/translation_android_wallet pull request #30
Opened 2020-02-02 11:58 UTC by caltv93

Danish translation plus english corrections

2020-02-02 12:03 UTC, decryp2kanon requested changes
pls remove english correction at this time. let's do one by one. do not together.

2020-02-02 12:25 UTC, cryptozeny approved these changes
thanks!

2020-02-02 13:26 UTC, decryp2kanon commented on da.json
> +	"addressBook.sendButton": "Send",
send is send in danish?

2020-02-02 13:27 UTC, decryp2kanon commented on da.json
> +	"addAddress.successAlert": "Succes!",
in danish?

2020-02-02 13:28 UTC, decryp2kanon commented on da.json
> +	"transactionDetails.alertTitle": "Send",
danish?

2020-02-02 13:28 UTC, decryp2kanon commented on da.json
> +	"send.successAlert": "Succes!",
danish?

2020-02-02 13:28 UTC, decryp2kanon commented on da.json
> +	"send.title": "Send",
danish?

2020-02-02 13:29 UTC, decryp2kanon approved these changes

2020-02-02 13:32 UTC, merged

2020-02-02 13:39 UTC, decryp2kanon commented
@caltv93 pls add your sugar address here!

2020-02-03 22:59 UTC, caltv93 commented
sugar1qe2lpuzz72u864e86gfjcmlsalmf3j3d5qe7vv0

2020-02-03 23:32 UTC, decryp2kanon commented
@AestheticSenpai will reward soon

thanks!